#include "EventService.h"
#include "../exceptions/AppException.h"
#include <regex>
EventService::EventService(EventRepository& repository,CustomerRepository& customerRepository):repository(repository),customerRepository(customerRepository){}
void EventService::validate(const Event& event) const { if(event.getEventCode().empty())throw ValidationException("Event ID is required.");if(event.getEventType().empty())throw ValidationException("Event type is required.");if(!regex_match(event.getEventDate(),regex("[0-9]{4}-[0-9]{2}-[0-9]{2}")))throw ValidationException("Date must use YYYY-MM-DD format.");if(!regex_match(event.getStartTime(),regex("[0-2][0-9]:[0-5][0-9]"))||!regex_match(event.getEndTime(),regex("[0-2][0-9]:[0-5][0-9]")))throw ValidationException("Time must use HH:MM format.");if(event.getStartTime()>=event.getEndTime())throw ValidationException("Start time must be before End time.");if(event.getGuestCount()<=0)throw ValidationException("Guest count must be greater than 0.");}
void EventService::create(const string& code,const string& customerCode,const string& type,const string& date,const string& startTime,const string& endTime,int guestCount){auto customer=customerRepository.findByCode(customerCode);if(!customer.has_value())throw EntityNotFoundException("Customer not found.");Event event(0,code,customer->getId(),type,date,startTime,endTime,guestCount,EventStatus::PLANNED);validate(event);if(repository.findByCode(code).has_value())throw BusinessException("Event ID already exists.");repository.save(event);}
Event EventService::findByCode(const string& code) const{auto event=repository.findByCode(code);if(!event.has_value())throw EntityNotFoundException("Event not found.");return *event;}
vector<Event> EventService::findAll() const{return repository.findAll();}
void EventService::update(const string& code,const string& customerCode,const string& type,const string& date,const string& startTime,const string& endTime,int guestCount,EventStatus status){Event event=findByCode(code);if(event.getStatus()==EventStatus::COMPLETED)throw BusinessException("Completed event cannot be updated.");auto customer=customerRepository.findByCode(customerCode);if(!customer.has_value())throw EntityNotFoundException("Customer not found.");event.setCustomerId(customer->getId());event.setEventType(type);event.setEventDate(date);event.setStartTime(startTime);event.setEndTime(endTime);event.setGuestCount(guestCount);event.setStatus(status);validate(event);repository.update(event);}
