#include "EventMenu.h"
#include "../utils/InputHelper.h"
#include "../utils/DisplayHelper.h"
#include "../exceptions/AppException.h"
#include <iostream>
using namespace std;
EventMenu::EventMenu(EventService& service):service(service){}
EventStatus EventMenu::readStatus(){string value=InputHelper::readString("Status (PLANNED/PREPARING/IN_PROGRESS/COMPLETED/CANCELLED): ");if(value=="PLANNED")return EventStatus::PLANNED;if(value=="PREPARING")return EventStatus::PREPARING;if(value=="IN_PROGRESS")return EventStatus::IN_PROGRESS;if(value=="COMPLETED")return EventStatus::COMPLETED;if(value=="CANCELLED")return EventStatus::CANCELLED;throw ValidationException("Invalid event status.");}
void EventMenu::create(){string code=InputHelper::readString("Event ID: ");string customerCode=InputHelper::readString("Customer ID: ");string type=InputHelper::readString("Event type: ");string date=InputHelper::readString("Date (YYYY-MM-DD): ");string startTime=InputHelper::readString("Start time (HH:MM): ");string endTime=InputHelper::readString("End time (HH:MM): ");int guestCount=InputHelper::readInt("Guest count: ");service.create(code,customerCode,type,date,startTime,endTime,guestCount);cout<<"Event created successfully.\n";}
void EventMenu::viewAll(){auto events=service.findAll();if(events.empty()){cout<<"No events found.\n";return;}for(const Event& event:events)cout<<event.getEventCode()<<" | "<<event.getEventType()<<" | "<<event.getEventDate()<<" "<<event.getStartTime()<<"-"<<event.getEndTime()<<" | Guests: "<<event.getGuestCount()<<"\n";}
void EventMenu::search(){Event event=service.findByCode(InputHelper::readString("Event ID: "));cout<<event.getEventCode()<<" | "<<event.getEventType()<<" | "<<event.getEventDate()<<" "<<event.getStartTime()<<"-"<<event.getEndTime()<<"\n";}
void EventMenu::update(){string code=InputHelper::readString("Event ID: ");string customerCode=InputHelper::readString("Customer ID: ");string type=InputHelper::readString("Event type: ");string date=InputHelper::readString("Date (YYYY-MM-DD): ");string startTime=InputHelper::readString("Start time (HH:MM): ");string endTime=InputHelper::readString("End time (HH:MM): ");int guestCount=InputHelper::readInt("Guest count: ");EventStatus status=readStatus();service.update(code,customerCode,type,date,startTime,endTime,guestCount,status);cout<<"Event updated successfully.\n";}
void EventMenu::show(){bool running=true;while(running){DisplayHelper::showHeader("EVENT MANAGEMENT");cout<<"1. Create Event\n2. View All Events\n3. Search Event\n4. Update Event\n5. Back\n";try{switch(InputHelper::readInt("Enter your choice: ")){case 1:create();break;case 2:viewAll();break;case 3:search();break;case 4:update();break;case 5:running=false;continue;default:DisplayHelper::showError("Invalid choice. Please try again.");}}catch(const AppException& exception){DisplayHelper::showError(exception.what());}DisplayHelper::pause();}}
