#include "EventRepository.h"
#include "../exceptions/AppException.h"

namespace {
string statusText(EventStatus status) { const char* texts[] = {"PLANNED", "PREPARING", "IN_PROGRESS", "COMPLETED", "CANCELLED"}; return texts[static_cast<int>(status)]; }
EventStatus eventStatus(const string& value) { if (value == "PREPARING") return EventStatus::PREPARING; if (value == "IN_PROGRESS") return EventStatus::IN_PROGRESS; if (value == "COMPLETED") return EventStatus::COMPLETED; if (value == "CANCELLED") return EventStatus::CANCELLED; return EventStatus::PLANNED; }
void prepareOrThrow(DatabaseManager& db, const char* sql, sqlite3_stmt** statement) { if (sqlite3_prepare_v2(db.getConnection(), sql, -1, statement, nullptr) != SQLITE_OK) throw DatabaseException("Database error: " + string(sqlite3_errmsg(db.getConnection()))); }
Event readEvent(sqlite3_stmt* statement) { return Event(sqlite3_column_int(statement, 0), reinterpret_cast<const char*>(sqlite3_column_text(statement, 1)), sqlite3_column_int(statement, 2), reinterpret_cast<const char*>(sqlite3_column_text(statement, 3)), reinterpret_cast<const char*>(sqlite3_column_text(statement, 4)), reinterpret_cast<const char*>(sqlite3_column_text(statement, 5)), reinterpret_cast<const char*>(sqlite3_column_text(statement, 6)), sqlite3_column_int(statement, 7), eventStatus(reinterpret_cast<const char*>(sqlite3_column_text(statement, 8)))); }
}
EventRepository::EventRepository(DatabaseManager& db) : db(db) {}
void EventRepository::save(const Event& event) { sqlite3_stmt* statement = nullptr; prepareOrThrow(db, "INSERT INTO events (event_code, customer_id, event_type, event_date, start_time, end_time, guest_count, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?);", &statement); string status = statusText(event.getStatus()); sqlite3_bind_text(statement,1,event.getEventCode().c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_int(statement,2,event.getCustomerId()); sqlite3_bind_text(statement,3,event.getEventType().c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(statement,4,event.getEventDate().c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(statement,5,event.getStartTime().c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_text(statement,6,event.getEndTime().c_str(),-1,SQLITE_TRANSIENT); sqlite3_bind_int(statement,7,event.getGuestCount()); sqlite3_bind_text(statement,8,status.c_str(),-1,SQLITE_TRANSIENT); if(sqlite3_step(statement)!=SQLITE_DONE){string error=sqlite3_errmsg(db.getConnection());sqlite3_finalize(statement);throw DatabaseException("Unable to save event: "+error);} sqlite3_finalize(statement); }
optional<Event> EventRepository::findByCode(const string& eventCode) const { sqlite3_stmt* statement=nullptr; prepareOrThrow(const_cast<DatabaseManager&>(db), "SELECT id,event_code,customer_id,event_type,event_date,start_time,end_time,guest_count,status FROM events WHERE event_code=?;", &statement); sqlite3_bind_text(statement,1,eventCode.c_str(),-1,SQLITE_TRANSIENT); int result=sqlite3_step(statement); if(result==SQLITE_ROW){Event event=readEvent(statement);sqlite3_finalize(statement);return event;}sqlite3_finalize(statement);return nullopt; }
vector<Event> EventRepository::findAll() const { vector<Event> events;sqlite3_stmt* statement=nullptr;prepareOrThrow(const_cast<DatabaseManager&>(db),"SELECT id,event_code,customer_id,event_type,event_date,start_time,end_time,guest_count,status FROM events ORDER BY event_date,event_code;",&statement);while(sqlite3_step(statement)==SQLITE_ROW)events.push_back(readEvent(statement));sqlite3_finalize(statement);return events; }
void EventRepository::update(const Event& event) { sqlite3_stmt* statement=nullptr;prepareOrThrow(db,"UPDATE events SET customer_id=?,event_type=?,event_date=?,start_time=?,end_time=?,guest_count=?,status=? WHERE event_code=?;",&statement);string status=statusText(event.getStatus());sqlite3_bind_int(statement,1,event.getCustomerId());sqlite3_bind_text(statement,2,event.getEventType().c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(statement,3,event.getEventDate().c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(statement,4,event.getStartTime().c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(statement,5,event.getEndTime().c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(statement,6,event.getGuestCount());sqlite3_bind_text(statement,7,status.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(statement,8,event.getEventCode().c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(statement)!=SQLITE_DONE){sqlite3_finalize(statement);throw DatabaseException("Unable to update event.");}sqlite3_finalize(statement); }
